services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-food
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  node:
    build: .
    container_name: ical-mensi-food
    ports:
      - "${NODE_PORT_EXTERN}:${NODE_PORT_INTERN}"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs

volumes:
  mongo_data: